# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tig/coding/scattnlay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tig/coding/scattnlay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tig/coding/scattnlay/CMakeFiles /Users/tig/coding/scattnlay//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tig/coding/scattnlay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scattnlay-dp

# Build rule for target.
scattnlay-dp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scattnlay-dp
.PHONY : scattnlay-dp

# fast build rule for target.
scattnlay-dp/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/scattnlay-dp.dir/build.make src/CMakeFiles/scattnlay-dp.dir/build
.PHONY : scattnlay-dp/fast

#=============================================================================
# Target rules for targets named fieldnlay-dp

# Build rule for target.
fieldnlay-dp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fieldnlay-dp
.PHONY : fieldnlay-dp

# fast build rule for target.
fieldnlay-dp/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/fieldnlay-dp.dir/build.make src/CMakeFiles/fieldnlay-dp.dir/build
.PHONY : fieldnlay-dp/fast

#=============================================================================
# Target rules for targets named scattnlay-mp

# Build rule for target.
scattnlay-mp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scattnlay-mp
.PHONY : scattnlay-mp

# fast build rule for target.
scattnlay-mp/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/scattnlay-mp.dir/build.make src/CMakeFiles/scattnlay-mp.dir/build
.PHONY : scattnlay-mp/fast

#=============================================================================
# Target rules for targets named fieldnlay-mp

# Build rule for target.
fieldnlay-mp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fieldnlay-mp
.PHONY : fieldnlay-mp

# fast build rule for target.
fieldnlay-mp/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/fieldnlay-mp.dir/build.make src/CMakeFiles/fieldnlay-mp.dir/build
.PHONY : fieldnlay-mp/fast

#=============================================================================
# Target rules for targets named test_near_field

# Build rule for target.
test_near_field: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_near_field
.PHONY : test_near_field

# fast build rule for target.
test_near_field/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_near_field.dir/build.make tests/CMakeFiles/test_near_field.dir/build
.PHONY : test_near_field/fast

#=============================================================================
# Target rules for targets named test_Riccati_Bessel_logarithmic_derivative

# Build rule for target.
test_Riccati_Bessel_logarithmic_derivative: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Riccati_Bessel_logarithmic_derivative
.PHONY : test_Riccati_Bessel_logarithmic_derivative

# fast build rule for target.
test_Riccati_Bessel_logarithmic_derivative/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_Riccati_Bessel_logarithmic_derivative.dir/build.make tests/CMakeFiles/test_Riccati_Bessel_logarithmic_derivative.dir/build
.PHONY : test_Riccati_Bessel_logarithmic_derivative/fast

#=============================================================================
# Target rules for targets named test_bulk_sphere

# Build rule for target.
test_bulk_sphere: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bulk_sphere
.PHONY : test_bulk_sphere

# fast build rule for target.
test_bulk_sphere/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_bulk_sphere.dir/build.make tests/CMakeFiles/test_bulk_sphere.dir/build
.PHONY : test_bulk_sphere/fast

#=============================================================================
# Target rules for targets named test_bulk_sphere_multi_precision

# Build rule for target.
test_bulk_sphere_multi_precision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bulk_sphere_multi_precision
.PHONY : test_bulk_sphere_multi_precision

# fast build rule for target.
test_bulk_sphere_multi_precision/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_bulk_sphere_multi_precision.dir/build.make tests/CMakeFiles/test_bulk_sphere_multi_precision.dir/build
.PHONY : test_bulk_sphere_multi_precision/fast

#=============================================================================
# Target rules for targets named test_near_field_multi_precision

# Build rule for target.
test_near_field_multi_precision: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_near_field_multi_precision
.PHONY : test_near_field_multi_precision

# fast build rule for target.
test_near_field_multi_precision/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_near_field_multi_precision.dir/build.make tests/CMakeFiles/test_near_field_multi_precision.dir/build
.PHONY : test_near_field_multi_precision/fast

#=============================================================================
# Target rules for targets named bench_special_functions

# Build rule for target.
bench_special_functions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_special_functions
.PHONY : bench_special_functions

# fast build rule for target.
bench_special_functions/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/bench_special_functions.dir/build.make tests/CMakeFiles/bench_special_functions.dir/build
.PHONY : bench_special_functions/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bench_special_functions"
	@echo "... fieldnlay-dp"
	@echo "... fieldnlay-mp"
	@echo "... scattnlay-dp"
	@echo "... scattnlay-mp"
	@echo "... test_Riccati_Bessel_logarithmic_derivative"
	@echo "... test_bulk_sphere"
	@echo "... test_bulk_sphere_multi_precision"
	@echo "... test_near_field"
	@echo "... test_near_field_multi_precision"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

